-- DEPARTMENTS
DELETE FROM NOTIFICATION.DEPARTMENT;
ALTER TABLE NOTIFICATION.DEPARTMENT AUTO_INCREMENT 1;
INSERT INTO NOTIFICATION.DEPARTMENT (CODE, NAME, ISACTIVE, CREATEDBY, CREATIONTS, LASTUPDATEDBY, LASTUPDATETS) VALUES ('NEWDEPT', 'Suttons NEW Project Department',  1, 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP);
