CREATE TABLE notification.auditlog
  ( 
     id                 BIGINT NOT NULL auto_increment, 
     version            BIGINT DEFAULT 1 NOT NULL,
     department_id      BIGINT,
     user_id            BIGINT,
     activitytype       VARCHAR(20) NOT NULL,
     activitydate       DATE,
     activityresource   VARCHAR(50), 
     activityresourceid BIGINT, 
     channel            VARCHAR(20) NOT NULL,
     description        LONGTEXT NOT NULL,
     ipaddress          VARCHAR(50) NOT NULL, 
     ispublic           CHAR(1) DEFAULT 1 NOT NULL, 
     createdby          BIGINT NOT NULL,
     creationts         DATETIME NOT NULL,
     lastupdatets       DATETIME NOT NULL,
     lastupdatedby      BIGINT NOT NULL,
     PRIMARY KEY (id)
  );

CREATE TABLE notification.department
  (
     id            BIGINT NOT NULL auto_increment,
     version       BIGINT DEFAULT 1 NOT NULL,
     code          VARCHAR(20) NOT NULL,
     name          VARCHAR(200) NOT NULL,
     isactive      CHAR(1) DEFAULT 0 NOT NULL,
     createdby     BIGINT NOT NULL,
     creationts    DATETIME NOT NULL,
     lastupdatets  DATETIME NOT NULL,
     lastupdatedby BIGINT NOT NULL,
     PRIMARY KEY (id)
  );

CREATE TABLE notification.lookup
  (
     id            BIGINT NOT NULL auto_increment,
     version       BIGINT DEFAULT 1 NOT NULL,
     type          VARCHAR(50) NOT NULL,
     label         VARCHAR(100) NOT NULL,
     value         VARCHAR(100) NOT NULL,
     sequence      BIGINT NOT NULL,
     createdby     BIGINT NOT NULL,
     creationts    DATETIME NOT NULL,
     lastupdatets  DATETIME NOT NULL,
     lastupdatedby BIGINT NOT NULL,
     PRIMARY KEY (id)
  );

CREATE TABLE notification.role
  (
     id            BIGINT NOT NULL auto_increment,
     version       BIGINT DEFAULT 1 NOT NULL,
     name          VARCHAR(50) NOT NULL,
     description   VARCHAR(200),
     createdby     BIGINT NOT NULL,
     creationts    DATETIME NOT NULL,
     lastupdatets  DATETIME NOT NULL,
     lastupdatedby BIGINT NOT NULL,
     PRIMARY KEY (id)
  );

CREATE TABLE notification.roleaccess
  (
     template_id BIGINT NOT NULL,
     role_id     BIGINT NOT NULL
  );

CREATE TABLE notification.sequencegenerator
  (
     id             BIGINT NOT NULL auto_increment,
     version        BIGINT DEFAULT 1 NOT NULL,
     name           VARCHAR(40) NOT NULL,
     sequencenumber BIGINT NOT NULL,
     PRIMARY KEY (id)
  );

CREATE TABLE notification.template
  (
     id                      BIGINT NOT NULL auto_increment,
     version                 BIGINT DEFAULT 1 NOT NULL,
     name                    VARCHAR(255),
     description             VARCHAR(255),
     access_level            BIGINT,
     lower_access_level_from BIGINT,
     lower_access_level_to   BIGINT,
     createdby               BIGINT NOT NULL,
     creationts              DATETIME NOT NULL,
     lastupdatets            DATETIME NOT NULL,
     lastupdatedby           BIGINT NOT NULL,
     PRIMARY KEY (id)
  );

CREATE TABLE notification.user
  (
     id                  BIGINT NOT NULL auto_increment,
     version             BIGINT DEFAULT 1 NOT NULL,
     username            VARCHAR(20),
     firstname           VARCHAR(50) NOT NULL,
     lastname            VARCHAR(50) NOT NULL,
     email               VARCHAR(100) NOT NULL,
     issystemadmin       CHAR(1) DEFAULT 0 NOT NULL,
     status              VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
     loginid             VARCHAR(20),
     password            VARCHAR(32),
     nonadloginsessionid VARCHAR(100),
     phonenumber         VARCHAR(30),
     lastloginip         VARCHAR(50),
     lastlogints         DATETIME,
     createdby           BIGINT NOT NULL,
     creationts          DATETIME NOT NULL,
     lastupdatets        DATETIME NOT NULL,
     lastupdatedby       BIGINT NOT NULL,
     PRIMARY KEY (id)
  );

CREATE TABLE notification.useraccess
  (
     id            BIGINT NOT NULL auto_increment,
     version       BIGINT DEFAULT 1 NOT NULL,
     department_id BIGINT,
     template_id   BIGINT,
     user_id       BIGINT,
     createdby     BIGINT NOT NULL,
     creationts    DATETIME NOT NULL,
     lastupdatets  DATETIME NOT NULL,
     lastupdatedby BIGINT NOT NULL,
     PRIMARY KEY (id)
  );

CREATE TABLE notification.versionhistory
  (
     version    VARCHAR(50) NOT NULL,
     creationts DATETIME NOT NULL,
     PRIMARY KEY (version)
  );

CREATE TABLE notification.company (
    id                BIGINT NOT NULL AUTO_INCREMENT,
    CREATEDBY         BIGINT NOT NULL,
    CREATIONTS        DATETIME NOT NULL,
    LASTUPDATETS      DATETIME NOT NULL,
    LASTUPDATEDBY     BIGINT NOT NULL,
    VERSION           BIGINT DEFAULT 1 NOT NULL,
    CODE              VARCHAR(50),
    NAME              VARCHAR(200) NOT NULL,
    STATUS            VARCHAR(20) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE notification.emaillog (
    id                  BIGINT NOT NULL AUTO_INCREMENT,
    createdby           BIGINT NOT NULL,
    creationts          DATETIME NOT NULL,
    lastupdatets        DATETIME NOT NULL,
    lastupdatedby       BIGINT NOT NULL,
    version             BIGINT DEFAULT 1 NOT NULL,
    status              VARCHAR(20) NOT NULL,
    mailrecipient_id    BIGINT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE notification.emaillogemployee (
    id                BIGINT NOT NULL AUTO_INCREMENT,
    createdby         BIGINT NOT NULL,
    creationts        DATETIME NOT NULL,
    lastupdatets      DATETIME NOT NULL,
    lastupdatedby     BIGINT NOT NULL,
    version           BIGINT DEFAULT 1 NOT NULL,
    terminationdate   DATE,
    emaillog_id       BIGINT NOT NULL,
    employee_id       BIGINT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE notification.employee (
    id                BIGINT NOT NULL AUTO_INCREMENT,
    createdby         BIGINT NOT NULL,
    creationts        DATETIME NOT NULL,
    lastupdatets      DATETIME NOT NULL,
    lastupdatedby     BIGINT NOT NULL,
    version           BIGINT DEFAULT 1 NOT NULL,
    description       VARCHAR(100),
    employeenumber    VARCHAR(20),
    firstname         VARCHAR(50),
    lastname          VARCHAR(50),
    position          VARCHAR(50),
    status            VARCHAR(20) NOT NULL,
    terminationdate   DATE,
    company_id        BIGINT,
    PRIMARY KEY (id)
);

CREATE TABLE notification.employeefile (
    id                  BIGINT NOT NULL AUTO_INCREMENT,
    createdby           BIGINT NOT NULL,
    creationts          DATETIME NOT NULL,
    lastupdatets        DATETIME NOT NULL,
    lastupdatedby       BIGINT NOT NULL,
    version             BIGINT DEFAULT 1 NOT NULL,
    fileurl             VARCHAR(255) NOT NULL,
    filename            VARCHAR(50) NOT NULL,
    status              VARCHAR(20) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE notification.employeefiledetail (
    id                  BIGINT NOT NULL AUTO_INCREMENT,
    createdby           BIGINT NOT NULL,
    creationts          DATETIME NOT NULL,
    lastupdatets        DATETIME NOT NULL,
    lastupdatedby       BIGINT NOT NULL,
    version             BIGINT DEFAULT 1 NOT NULL,
    companycode         VARCHAR(50),
    description         VARCHAR(100),
    employeenumber      VARCHAR(20),
    firstname           VARCHAR(50),
    lastname            VARCHAR(50),
    position            VARCHAR(50),
    status              VARCHAR(20) NOT NULL,
    terminationdate     DATE,
    employeefile_id     BIGINT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE notification.mailrecipient (
    id                  BIGINT NOT NULL AUTO_INCREMENT,
    createdby           BIGINT NOT NULL,
    creationts          DATETIME NOT NULL,
    lastupdatets        DATETIME NOT NULL,
    lastupdatedby       BIGINT NOT NULL,
    version             BIGINT DEFAULT 1 NOT NULL,
    email               VARCHAR(100) NOT NULL,
    name                VARCHAR(100),
    type                VARCHAR(20) NOT NULL,
    status              VARCHAR(20) NOT NULL,
    company_id          BIGINT,
    PRIMARY KEY (id)
);

CREATE TABLE notification.terminationnotificationconfig (
    id                    BIGINT NOT NULL AUTO_INCREMENT,
    createdby             BIGINT NOT NULL,
    creationts            DATETIME NOT NULL,
    lastupdatets          DATETIME NOT NULL,
    lastupdatedby         BIGINT NOT NULL,
    version               BIGINT DEFAULT 1 NOT NULL,
    daystoterminationfrom BIGINT NOT NULL,
    daystoterminationto   BIGINT NOT NULL,
    description           VARCHAR(100) NOT NULL,
    sequence              BIGINT NOT NULL,
    type                  VARCHAR(20) NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX index_resource ON notification.auditlog (activityresource, activityresourceid);

ALTER TABLE notification.user
  ADD CONSTRAINT uk_eyb74enjxbapeoiespumr1k2s UNIQUE (loginid);

ALTER TABLE notification.user
  ADD CONSTRAINT uk_lb5yrvw2c22im784wwrpwuq06 UNIQUE (username);

ALTER TABLE notification.auditlog
  ADD CONSTRAINT fk_auditlog_department FOREIGN KEY (department_id) REFERENCES
  notification.department (id);

ALTER TABLE notification.auditlog
  ADD CONSTRAINT fk_auditlog_user FOREIGN KEY (user_id) REFERENCES
  notification.user (id);

ALTER TABLE notification.roleaccess
  ADD CONSTRAINT fk_6aw04qghku2aul22dbnwq5ply FOREIGN KEY (role_id) REFERENCES
  notification.role (id);

ALTER TABLE notification.roleaccess
  ADD CONSTRAINT fk_frphauq5d527tbth8ratq8j8s FOREIGN KEY (template_id)
  REFERENCES notification.template (id);

ALTER TABLE notification.useraccess
  ADD CONSTRAINT fk_useraccess_department FOREIGN KEY (department_id) REFERENCES
  notification.department (id);

ALTER TABLE notification.useraccess
  ADD CONSTRAINT fk_useraccess_template FOREIGN KEY (template_id) REFERENCES
  notification.template (id);

ALTER TABLE notification.useraccess
  ADD CONSTRAINT fk_useraccess_user FOREIGN KEY (user_id) REFERENCES
  notification.user (id);

ALTER TABLE notification.emaillog
    ADD CONSTRAINT fk_emaillog_mailrecipient
    FOREIGN KEY (mailrecipient_id) REFERENCES notification.mailrecipient (id);

ALTER TABLE notification.emaillogemployee
    ADD CONSTRAINT fk_emaillogemployee_emaillog
    FOREIGN KEY (emaillog_id) REFERENCES notification.emaillog (id);

ALTER TABLE notification.emaillogemployee
    ADD CONSTRAINT fk_emaillogemployee_employee
    FOREIGN KEY (employee_id) REFERENCES notification.employee (id);

ALTER TABLE notification.employee
    ADD CONSTRAINT fk_employee_company
    FOREIGN KEY (company_id) REFERENCES notification.company (id);

ALTER TABLE notification.employeefiledetail
    ADD CONSTRAINT fk_employeefiledetail_employeefile
    FOREIGN KEY (employeefile_id) REFERENCES notification.employeefile (id);

ALTER TABLE notification.mailrecipient
    ADD CONSTRAINT fk_mailrecipient_company
    FOREIGN KEY (company_id) REFERENCES notification.company (id);

-- ---------------
-- Initial Date
-- ---------------

-- VERSIONHISTORY
INSERT INTO notification.versionhistory VALUES('1.0.0.0', CURRENT_TIMESTAMP);

-- TEMPLATES
DELETE FROM NOTIFICATION.TEMPLATE;
ALTER TABLE NOTIFICATION.TEMPLATE AUTO_INCREMENT 1;
INSERT INTO NOTIFICATION.TEMPLATE (NAME, DESCRIPTION, ACCESS_LEVEL, LOWER_ACCESS_LEVEL_FROM, LOWER_ACCESS_LEVEL_TO, CREATEDBY, CREATIONTS, LASTUPDATEDBY, LASTUPDATETS) VALUES ('NOTIFICATION_ADMIN','ADMINISTRATOR', 9000, 0, 9999, 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP);

-- ----------------------
-- ROLE CONFIGURATION --
-- ----------------------
DELETE FROM NOTIFICATION.ROLE;
ALTER TABLE NOTIFICATION.ROLE AUTO_INCREMENT 1;

-- COMMON RESOURCE (LOOKUP)
INSERT INTO NOTIFICATION.ROLE (NAME, DESCRIPTION, CREATEDBY, CREATIONTS, LASTUPDATEDBY, LASTUPDATETS) VALUES ('LOOKUP_LIST','', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP);
INSERT INTO NOTIFICATION.ROLEACCESS (TEMPLATE_ID, ROLE_ID) SELECT T.ID, R.ID FROM NOTIFICATION.TEMPLATE T, NOTIFICATION.ROLE R WHERE R.NAME = 'LOOKUP_LIST' AND T.NAME = 'NOTIFICATION_ADMIN';

-- DEPARTMENT RESOURCE
INSERT INTO NOTIFICATION.ROLE (NAME, DESCRIPTION, CREATEDBY, CREATIONTS, LASTUPDATEDBY, LASTUPDATETS) VALUES ('DEPARTMENT_LIST','', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP);
INSERT INTO NOTIFICATION.ROLEACCESS (TEMPLATE_ID, ROLE_ID) SELECT T.ID, R.ID FROM NOTIFICATION.TEMPLATE T, NOTIFICATION.ROLE R WHERE R.NAME = 'DEPARTMENT_LIST' AND T.NAME = 'NOTIFICATION_ADMIN';

-- ROLE RESOURCE
INSERT INTO NOTIFICATION.ROLE (NAME, DESCRIPTION, CREATEDBY, CREATIONTS, LASTUPDATEDBY, LASTUPDATETS) VALUES ('ROLE_VIEW','', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP);
INSERT INTO NOTIFICATION.ROLE (NAME, DESCRIPTION, CREATEDBY, CREATIONTS, LASTUPDATEDBY, LASTUPDATETS) VALUES ('ROLE_LIST','', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP);
INSERT INTO NOTIFICATION.ROLE (NAME, DESCRIPTION, CREATEDBY, CREATIONTS, LASTUPDATEDBY, LASTUPDATETS) VALUES ('ROLE_EDIT','', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP);
INSERT INTO NOTIFICATION.ROLE (NAME, DESCRIPTION, CREATEDBY, CREATIONTS, LASTUPDATEDBY, LASTUPDATETS) VALUES ('ROLE_ADD','', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP);

-- TEMPLATE RESOURCE
INSERT INTO NOTIFICATION.ROLE (NAME, DESCRIPTION, CREATEDBY, CREATIONTS, LASTUPDATEDBY, LASTUPDATETS) VALUES ('TEMPLATE_LIST','', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP);
INSERT INTO NOTIFICATION.ROLEACCESS (TEMPLATE_ID, ROLE_ID) SELECT T.ID, R.ID FROM NOTIFICATION.TEMPLATE T, NOTIFICATION.ROLE R WHERE R.NAME = 'TEMPLATE_LIST' AND T.NAME = 'NOTIFICATION_ADMIN';

INSERT INTO NOTIFICATION.ROLE (NAME, DESCRIPTION, CREATEDBY, CREATIONTS, LASTUPDATEDBY, LASTUPDATETS) VALUES ('TEMPLATE_VIEW','', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP);
INSERT INTO NOTIFICATION.ROLE (NAME, DESCRIPTION, CREATEDBY, CREATIONTS, LASTUPDATEDBY, LASTUPDATETS) VALUES ('TEMPLATE_EDIT','', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP);
INSERT INTO NOTIFICATION.ROLE (NAME, DESCRIPTION, CREATEDBY, CREATIONTS, LASTUPDATEDBY, LASTUPDATETS) VALUES ('TEMPLATE_ADD','', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP);

-- USERACCESS RESOURCE
INSERT INTO NOTIFICATION.ROLE (NAME, DESCRIPTION, CREATEDBY, CREATIONTS, LASTUPDATEDBY, LASTUPDATETS) VALUES ('USER_ACCESS_LIST','', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP);
INSERT INTO NOTIFICATION.ROLEACCESS (TEMPLATE_ID, ROLE_ID) SELECT T.ID, R.ID FROM NOTIFICATION.TEMPLATE T, NOTIFICATION.ROLE R WHERE R.NAME = 'USER_ACCESS_LIST' AND T.NAME = 'NOTIFICATION_ADMIN';
INSERT INTO NOTIFICATION.ROLE (NAME, DESCRIPTION, CREATEDBY, CREATIONTS, LASTUPDATEDBY, LASTUPDATETS) VALUES ('USER_ACCESS_VIEW','', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP);
INSERT INTO NOTIFICATION.ROLEACCESS (TEMPLATE_ID, ROLE_ID) SELECT T.ID, R.ID FROM NOTIFICATION.TEMPLATE T, NOTIFICATION.ROLE R WHERE R.NAME = 'USER_ACCESS_VIEW' AND T.NAME = 'NOTIFICATION_ADMIN';
INSERT INTO NOTIFICATION.ROLE (NAME, DESCRIPTION, CREATEDBY, CREATIONTS, LASTUPDATEDBY, LASTUPDATETS) VALUES ('USER_ACCESS_EDIT','', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP);
INSERT INTO NOTIFICATION.ROLEACCESS (TEMPLATE_ID, ROLE_ID) SELECT T.ID, R.ID FROM NOTIFICATION.TEMPLATE T, NOTIFICATION.ROLE R WHERE R.NAME = 'USER_ACCESS_EDIT' AND T.NAME = 'NOTIFICATION_ADMIN';
INSERT INTO NOTIFICATION.ROLE (NAME, DESCRIPTION, CREATEDBY, CREATIONTS, LASTUPDATEDBY, LASTUPDATETS) VALUES ('USER_ACCESS_ADD','', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP);
INSERT INTO NOTIFICATION.ROLEACCESS (TEMPLATE_ID, ROLE_ID) SELECT T.ID, R.ID FROM NOTIFICATION.TEMPLATE T, NOTIFICATION.ROLE R WHERE R.NAME = 'USER_ACCESS_ADD' AND T.NAME = 'NOTIFICATION_ADMIN';
INSERT INTO NOTIFICATION.ROLE (NAME, DESCRIPTION, CREATEDBY, CREATIONTS, LASTUPDATEDBY, LASTUPDATETS) VALUES ('USER_ACCESS_DELETE','', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP);
INSERT INTO NOTIFICATION.ROLEACCESS (TEMPLATE_ID, ROLE_ID) SELECT T.ID, R.ID FROM NOTIFICATION.TEMPLATE T, NOTIFICATION.ROLE R WHERE R.NAME = 'USER_ACCESS_DELETE' AND T.NAME = 'NOTIFICATION_ADMIN';

-- USER RESOURCE
INSERT INTO NOTIFICATION.ROLE (NAME, DESCRIPTION, CREATEDBY, CREATIONTS, LASTUPDATEDBY, LASTUPDATETS) VALUES ('USER_VIEW','', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP);
INSERT INTO NOTIFICATION.ROLEACCESS (TEMPLATE_ID, ROLE_ID) SELECT T.ID, R.ID FROM NOTIFICATION.TEMPLATE T, NOTIFICATION.ROLE R WHERE R.NAME = 'USER_VIEW' AND T.NAME = 'NOTIFICATION_ADMIN';
INSERT INTO NOTIFICATION.ROLE (NAME, DESCRIPTION, CREATEDBY, CREATIONTS, LASTUPDATEDBY, LASTUPDATETS) VALUES ('USER_LIST','', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP);
INSERT INTO NOTIFICATION.ROLEACCESS (TEMPLATE_ID, ROLE_ID) SELECT T.ID, R.ID FROM NOTIFICATION.TEMPLATE T, NOTIFICATION.ROLE R WHERE R.NAME = 'USER_LIST' AND T.NAME = 'NOTIFICATION_ADMIN';
INSERT INTO NOTIFICATION.ROLE (NAME, DESCRIPTION, CREATEDBY, CREATIONTS, LASTUPDATEDBY, LASTUPDATETS) VALUES ('USER_EDIT','', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP);
INSERT INTO NOTIFICATION.ROLEACCESS (TEMPLATE_ID, ROLE_ID) SELECT T.ID, R.ID FROM NOTIFICATION.TEMPLATE T, NOTIFICATION.ROLE R WHERE R.NAME = 'USER_EDIT' AND T.NAME = 'NOTIFICATION_ADMIN';
INSERT INTO NOTIFICATION.ROLE (NAME, DESCRIPTION, CREATEDBY, CREATIONTS, LASTUPDATEDBY, LASTUPDATETS) VALUES ('USER_ADD','', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP);
INSERT INTO NOTIFICATION.ROLEACCESS (TEMPLATE_ID, ROLE_ID) SELECT T.ID, R.ID FROM NOTIFICATION.TEMPLATE T, NOTIFICATION.ROLE R WHERE R.NAME = 'USER_ADD' AND T.NAME = 'NOTIFICATION_ADMIN';
INSERT INTO NOTIFICATION.ROLE (NAME, DESCRIPTION, CREATEDBY, CREATIONTS, LASTUPDATEDBY, LASTUPDATETS) VALUES ('USER_DISABLE','', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP);
INSERT INTO NOTIFICATION.ROLEACCESS (TEMPLATE_ID, ROLE_ID) SELECT T.ID, R.ID FROM NOTIFICATION.TEMPLATE T, NOTIFICATION.ROLE R WHERE R.NAME = 'USER_DISABLE' AND T.NAME = 'NOTIFICATION_ADMIN';

-- AUDIT LOG
INSERT INTO NOTIFICATION.ROLE (NAME, DESCRIPTION, CREATEDBY, CREATIONTS, LASTUPDATEDBY, LASTUPDATETS) VALUES ('AUDIT_LOG_VIEW','', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP);
INSERT INTO NOTIFICATION.ROLEACCESS (TEMPLATE_ID, ROLE_ID) SELECT T.ID, R.ID FROM NOTIFICATION.TEMPLATE T, NOTIFICATION.ROLE R WHERE R.NAME = 'AUDIT_LOG_VIEW' AND T.NAME = 'NOTIFICATION_ADMIN';
INSERT INTO NOTIFICATION.ROLE (NAME, DESCRIPTION, CREATEDBY, CREATIONTS, LASTUPDATEDBY, LASTUPDATETS) VALUES ('AUDIT_LOG_LIST','', 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP);
INSERT INTO NOTIFICATION.ROLEACCESS (TEMPLATE_ID, ROLE_ID) SELECT T.ID, R.ID FROM NOTIFICATION.TEMPLATE T, NOTIFICATION.ROLE R WHERE R.NAME = 'AUDIT_LOG_LIST' AND T.NAME = 'NOTIFICATION_ADMIN';

-- User Status
INSERT INTO NOTIFICATION.LOOKUP (TYPE, LABEL, VALUE, SEQUENCE, CREATEDBY, CREATIONTS, LASTUPDATETS, LASTUPDATEDBY) VALUES ('USER_STATUS', 'ACTIVE', 'ACTIVE', 0, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO NOTIFICATION.LOOKUP (TYPE, LABEL, VALUE, SEQUENCE, CREATEDBY, CREATIONTS, LASTUPDATETS, LASTUPDATEDBY) VALUES ('USER_STATUS', 'INACTIVE', 'INACTIVE', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);

-- -------------
-- USER --
-- -------------
DELETE FROM NOTIFICATION.USER;
ALTER TABLE NOTIFICATION.USER AUTO_INCREMENT 1;
INSERT INTO NOTIFICATION.USER (USERNAME, FIRSTNAME, LASTNAME, EMAIL, STATUS, ISSYSTEMADMIN, PHONENUMBER, LOGINID, CREATEDBY, CREATIONTS, LASTUPDATETS, LASTUPDATEDBY) VALUES ('system', 'System', '', 'vlssystem@suttons.com.au', 'ACTIVE', '1',  '04', '1', '1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1');
INSERT INTO NOTIFICATION.USER (USERNAME, FIRSTNAME, LASTNAME, EMAIL, STATUS, ISSYSTEMADMIN, PHONENUMBER, LOGINID, CREATEDBY, CREATIONTS, LASTUPDATETS, LASTUPDATEDBY) VALUES ('nirmala.batuwitage', 'Nirmala', 'Batuwitage', 'nirmala.bawutitage@suttons.com.au', 'ACTIVE', '1',  '04', '2', '1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1');
INSERT INTO NOTIFICATION.USER (USERNAME, FIRSTNAME, LASTNAME, EMAIL, STATUS, ISSYSTEMADMIN, PHONENUMBER, LOGINID, CREATEDBY, CREATIONTS, LASTUPDATETS, LASTUPDATEDBY) VALUES ('puvi.nadesan', 'Puvi', 'Nadesan', 'puvi.nadesan@suttons.com.au', 'ACTIVE', '1',  '04', '3', '1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1');
INSERT INTO NOTIFICATION.USER (USERNAME, FIRSTNAME, LASTNAME, EMAIL, STATUS, ISSYSTEMADMIN, PHONENUMBER, LOGINID, CREATEDBY, CREATIONTS, LASTUPDATETS, LASTUPDATEDBY) VALUES ('teddy.wong', 'Teddy', 'Wong', 'teddy.wong@suttons.com.au', 'ACTIVE', '1',  '04', '4', '1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1');
INSERT INTO NOTIFICATION.USER (USERNAME, FIRSTNAME, LASTNAME, EMAIL, STATUS, ISSYSTEMADMIN, PHONENUMBER, LOGINID, CREATEDBY, CREATIONTS, LASTUPDATETS, LASTUPDATEDBY) VALUES ('andre.macalino', 'Andre', 'Macalino', 'andre.macalino@suttons.com.au', 'ACTIVE', '1',  '04', '5', '1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1');
INSERT INTO NOTIFICATION.USER (USERNAME, FIRSTNAME, LASTNAME, EMAIL, STATUS, ISSYSTEMADMIN, PHONENUMBER, LOGINID, CREATEDBY, CREATIONTS, LASTUPDATETS, LASTUPDATEDBY) VALUES ('sandesh.shetty', 'Sandesh', 'Shetty', 'sandesh.shetty@suttons.com.au', 'ACTIVE', '1',  '04', '6', '1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1');
INSERT INTO NOTIFICATION.USER (USERNAME, FIRSTNAME, LASTNAME, EMAIL, STATUS, ISSYSTEMADMIN, PHONENUMBER, LOGINID, CREATEDBY, CREATIONTS, LASTUPDATETS, LASTUPDATEDBY) VALUES ('tim.chan', 'Tim', 'Chan', 'tchan@suttons.com.au', 'ACTIVE', '1',  '04', '7', '1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1');
INSERT INTO NOTIFICATION.USER (USERNAME, FIRSTNAME, LASTNAME, EMAIL, STATUS, ISSYSTEMADMIN, PHONENUMBER, LOGINID, CREATEDBY, CREATIONTS, LASTUPDATETS, LASTUPDATEDBY) VALUES ('surinder.rana', 'Surinder', 'Rana', 'srana@suttons.com.au', 'ACTIVE', '1',  '04', '8', '1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1');

-- DEPARTMENTS
DELETE FROM NOTIFICATION.DEPARTMENT;
ALTER TABLE NOTIFICATION.DEPARTMENT AUTO_INCREMENT 1;
INSERT INTO NOTIFICATION.DEPARTMENT (CODE, NAME, ISACTIVE, CREATEDBY, CREATIONTS, LASTUPDATEDBY, LASTUPDATETS) VALUES ('MIS', 'MIS',  1, 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP);

-- Create initial user-access
DELETE FROM NOTIFICATION.USERACCESS;
ALTER TABLE NOTIFICATION.USERACCESS AUTO_INCREMENT 1;
INSERT INTO NOTIFICATION.USERACCESS (USER_ID, DEPARTMENT_ID, TEMPLATE_ID, CREATEDBY, CREATIONTS, LASTUPDATETS, LASTUPDATEDBY) VALUES (2,1,1, '1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1');
INSERT INTO NOTIFICATION.USERACCESS (USER_ID, DEPARTMENT_ID, TEMPLATE_ID, CREATEDBY, CREATIONTS, LASTUPDATETS, LASTUPDATEDBY) VALUES (3,1,1, '1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1');

-- Company Status
INSERT INTO NOTIFICATION.LOOKUP (TYPE, LABEL, VALUE, SEQUENCE, CREATEDBY, CREATIONTS, LASTUPDATETS, LASTUPDATEDBY) VALUES ('COMPANY_STATUS', 'ACTIVE', 'ACTIVE', 0, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO NOTIFICATION.LOOKUP (TYPE, LABEL, VALUE, SEQUENCE, CREATEDBY, CREATIONTS, LASTUPDATETS, LASTUPDATEDBY) VALUES ('COMPANY_STATUS', 'INACTIVE', 'INACTIVE', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);

-- Mail Recipient Status
INSERT INTO NOTIFICATION.LOOKUP (TYPE, LABEL, VALUE, SEQUENCE, CREATEDBY, CREATIONTS, LASTUPDATETS, LASTUPDATEDBY) VALUES ('MAILRECIPIENT_STATUS', 'ACTIVE', 'ACTIVE', 0, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO NOTIFICATION.LOOKUP (TYPE, LABEL, VALUE, SEQUENCE, CREATEDBY, CREATIONTS, LASTUPDATETS, LASTUPDATEDBY) VALUES ('MAILRECIPIENT_STATUS', 'INACTIVE', 'INACTIVE', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);

-- Mail Recipient Type
INSERT INTO NOTIFICATION.LOOKUP (TYPE, LABEL, VALUE, SEQUENCE, CREATEDBY, CREATIONTS, LASTUPDATETS, LASTUPDATEDBY) VALUES ('MAILRECIPIENT_TYPE', 'GLOBAL', 'GLOBAL', 0, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO NOTIFICATION.LOOKUP (TYPE, LABEL, VALUE, SEQUENCE, CREATEDBY, CREATIONTS, LASTUPDATETS, LASTUPDATEDBY) VALUES ('MAILRECIPIENT_TYPE', 'COMPANY', 'COMPANY', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);


-- Companies
INSERT INTO NOTIFICATION.COMPANY (CODE, NAME, STATUS, CREATEDBY, CREATIONTS, LASTUPDATETS, LASTUPDATEDBY) VALUES ('303', 'T/A SUTTONS MOTORS MANAGEMENT', 'ACTIVE', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO NOTIFICATION.COMPANY (CODE, NAME, STATUS, CREATEDBY, CREATIONTS, LASTUPDATETS, LASTUPDATEDBY) VALUES ('388', 'T/A SELECT FLEET MANAGEMENT', 'ACTIVE', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO NOTIFICATION.COMPANY (CODE, NAME, STATUS, CREATEDBY, CREATIONTS, LASTUPDATETS, LASTUPDATEDBY) VALUES ('1802', 'T/A SUTTONS PARTS', 'ACTIVE', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO NOTIFICATION.COMPANY (CODE, NAME, STATUS, CREATEDBY, CREATIONTS, LASTUPDATETS, LASTUPDATEDBY) VALUES ('701', 'T/A CLERKNESS PASTORAL COMPANY', 'ACTIVE', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO NOTIFICATION.COMPANY (CODE, NAME, STATUS, CREATEDBY, CREATIONTS, LASTUPDATETS, LASTUPDATEDBY) VALUES ('2717', 'SUTTONS MOTORS T/A SUTTONS CITY', 'ACTIVE', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO NOTIFICATION.COMPANY (CODE, NAME, STATUS, CREATEDBY, CREATIONTS, LASTUPDATETS, LASTUPDATEDBY) VALUES ('3038', 'T/A SYDNEY CITY SUBARU', 'ACTIVE', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO NOTIFICATION.COMPANY (CODE, NAME, STATUS, CREATEDBY, CREATIONTS, LASTUPDATETS, LASTUPDATEDBY) VALUES ('2812', 'T/A SUTTONS MOTORS ARNCLIFFE', 'ACTIVE', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO NOTIFICATION.COMPANY (CODE, NAME, STATUS, CREATEDBY, CREATIONTS, LASTUPDATETS, LASTUPDATEDBY) VALUES ('3214', 'T/A MOSMAN TOYOTA', 'ACTIVE', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO NOTIFICATION.COMPANY (CODE, NAME, STATUS, CREATEDBY, CREATIONTS, LASTUPDATETS, LASTUPDATEDBY) VALUES ('318', 'T/A SCUDERIA VELOCE MOTORS', 'ACTIVE', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO NOTIFICATION.COMPANY (CODE, NAME, STATUS, CREATEDBY, CREATIONTS, LASTUPDATETS, LASTUPDATEDBY) VALUES ('2901', 'T/A SUTTONS MOTORS HOMEBUSH', 'ACTIVE', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO NOTIFICATION.COMPANY (CODE, NAME, STATUS, CREATEDBY, CREATIONTS, LASTUPDATETS, LASTUPDATEDBY) VALUES ('3031', 'T/A SUTTONS SUBARU ROSEBERY', 'ACTIVE', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO NOTIFICATION.COMPANY (CODE, NAME, STATUS, CREATEDBY, CREATIONTS, LASTUPDATETS, LASTUPDATEDBY) VALUES ('361', 'T/A AUTO AUCTIONS', 'ACTIVE', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO NOTIFICATION.COMPANY (CODE, NAME, STATUS, CREATEDBY, CREATIONTS, LASTUPDATETS, LASTUPDATEDBY) VALUES ('311', 'T/A CONCORD JAGUAR LANDROVER', 'ACTIVE', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO NOTIFICATION.COMPANY (CODE, NAME, STATUS, CREATEDBY, CREATIONTS, LASTUPDATETS, LASTUPDATEDBY) VALUES ('341', 'T/A SCUDERIA VELOCE VOLVO CARS', 'ACTIVE', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO NOTIFICATION.COMPANY (CODE, NAME, STATUS, CREATEDBY, CREATIONTS, LASTUPDATETS, LASTUPDATEDBY) VALUES ('315', 'T/A WESTERN TOYOTA/CITY HINO', 'ACTIVE', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);


-- Add Notification Sent Flag
ALTER TABLE notification.employee
    ADD COLUMN notificationsent CHAR(1) NULL DEFAULT '0' AFTER terminationdate;
